feat: добавлен весь функционал спринта #13
na1mov/java-shareit pull request #1
Opened 2023-04-22 14:04 UTC by na1mov

Добавлен весь функционал спринта #13

2023-04-23 11:17 UTC, ohelly requested changes
Привет! Отлично выполненная работа, все работает корректно. Есть пара не бьольших замечаний, которые необходимо исправить. Также я оставил ряд рекомендаций на которые стоит обратить внимание. Также рекомендую попробовать написать мапперы с использованием мапстракта, прикольная штука)
https://www.baeldung.com/mapstruct

2023-04-23 11:17 UTC, ohelly commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private String status;
Рекомендация: Поле статус можно сделать енамом.

2023-04-23 11:17 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private Long id;
Рекомендация: Модификатор private можно не указывать, так как его выставит аннотация ломбока ``@Value``
Аналогично с UserDto

2023-04-23 11:17 UTC, ohelly commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
> +package ru.practicum.shareit.user;
Рекомендация: Маппер лучше вынести в отдельный пакет mapper

2023-04-23 11:17 UTC, ohelly commented on src/main/java/ru/practicum/shareit/user/UserController.java
>  package ru.practicum.shareit.user;
Рекомендация: Для классов контроллеров также будет лучше создать отдельный пакет

2023-04-23 11:17 UTC, ohelly commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        log.info(String.format("Удаление пользователя c ID:%d", userId));
Необходимо исправить: Отсутсвует проверка на то, что пользователь не существует

2023-04-23 11:17 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        itemRepository.delete(itemId);
Необходимо исправить: Также отсутсвует проверка на то, существует ли вещь.

2023-04-25 07:05 UTC, na1mov commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private String status;
Как раз в теории следующего спринта прочитал, что статус можно сделать enum, выполню эту рекомендацию в спринте, когда надо будет добавлять booking :)

2023-04-25 07:06 UTC, na1mov commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private Long id;
Исправил

2023-04-25 07:06 UTC, na1mov commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
> +package ru.practicum.shareit.user;
Исправил

2023-04-25 07:06 UTC, na1mov commented on src/main/java/ru/practicum/shareit/user/UserController.java
>  package ru.practicum.shareit.user;
Исправил

2023-04-25 07:06 UTC, na1mov commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        log.info(String.format("Удаление пользователя c ID:%d", userId));
Исправил

2023-04-25 07:06 UTC, na1mov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        itemRepository.delete(itemId);
Исправил

2023-04-25 16:43 UTC, ohelly approved these changes
Привет! Все супер, исправлены все замечания. Работу принимаю, можно двигаться дальше!

2023-04-26 04:59 UTC, merged