feat: добавлен весь функционал спринта #15
na1mov/java-shareit pull request #3
Opened 2023-05-15 21:50 UTC by na1mov

добавлен весь функционал спринта #15

2023-05-15 23:23 UTC, na1mov commented
Я просто не понимаю, что такое branches covered ratio, где его найти и как его улучшить...
Warning:  Rule violated for bundle shareit: branches covered ratio is 0.5, but expected minimum is 0.6

2023-05-16 18:34 UTC, ohelly requested changes
Привет! Отличная работа, в целом все работает корректно. Но есть одно замечание - не добавлена пагинация для двух методов GET /items и GET /items/search.

2023-05-16 18:34 UTC, ohelly commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        if (requestIdToItemList.containsKey(itemRequestId)) {
Рекомендация: Для того, чтобы не использовать условие с операций contains, можно использовать метод у мапы - getOrDefault

2023-05-16 21:24 UTC, na1mov commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        if (requestIdToItemList.containsKey(itemRequestId)) {
Понял, принял) в предыдущих спринтах использовал, а в этом почему-то забыл про getOrDefault

2023-05-16 21:25 UTC, na1mov commented
Добавлена пагинация для двух методов GET /items и GET /items/search

2023-05-17 18:13 UTC, ohelly approved these changes
Привет! Все супер, исправлены все замечания. Работу принимаю, можно двигаться дальше!

2023-05-18 09:19 UTC, na1mov commented
Спасибо за ревью :)

2023-05-18 09:19 UTC, merged